/**
 * This class is generated by jOOQ
 */
package model.mapping;


import javax.annotation.Generated;

import model.mapping.tables.LoggingTable;
import model.mapping.tables.RecipeIngredientTable;
import model.mapping.tables.RecipeInstructionTable;
import model.mapping.tables.RecipeTable;
import model.mapping.tables.UserTable;


/**
 * Convenience access to all tables in vegan_kitchen_api
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table vegan_kitchen_api.logging
	 */
	public static final LoggingTable LOGGING = model.mapping.tables.LoggingTable.LOGGING;

	/**
	 * The table vegan_kitchen_api.recipe
	 */
	public static final RecipeTable RECIPE = model.mapping.tables.RecipeTable.RECIPE;

	/**
	 * The table vegan_kitchen_api.recipe_ingredient
	 */
	public static final RecipeIngredientTable RECIPE_INGREDIENT = model.mapping.tables.RecipeIngredientTable.RECIPE_INGREDIENT;

	/**
	 * The table vegan_kitchen_api.recipe_instruction
	 */
	public static final RecipeInstructionTable RECIPE_INSTRUCTION = model.mapping.tables.RecipeInstructionTable.RECIPE_INSTRUCTION;

	/**
	 * The table vegan_kitchen_api.user
	 */
	public static final UserTable USER = model.mapping.tables.UserTable.USER;
}
