/**
 * This class is generated by jOOQ
 */
package model.mapping;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import model.mapping.tables.LoggingTable;
import model.mapping.tables.RecipeIngredientTable;
import model.mapping.tables.RecipeInstructionTable;
import model.mapping.tables.RecipeTable;
import model.mapping.tables.UserTable;

import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VeganKitchenApiSchema extends SchemaImpl {

	private static final long serialVersionUID = 991244956;

	/**
	 * The reference instance of <code>vegan_kitchen_api</code>
	 */
	public static final VeganKitchenApiSchema VEGAN_KITCHEN_API = new VeganKitchenApiSchema();

	/**
	 * No further instances allowed
	 */
	private VeganKitchenApiSchema() {
		super("vegan_kitchen_api");
	}

	@Override
	public final List<Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0() {
		return Arrays.<Table<?>>asList(
			LoggingTable.LOGGING,
			RecipeTable.RECIPE,
			RecipeIngredientTable.RECIPE_INGREDIENT,
			RecipeInstructionTable.RECIPE_INSTRUCTION,
			UserTable.USER);
	}
}
