/**
 * This class is generated by jOOQ
 */
package model.mapping.tables.records;


import javax.annotation.Generated;

import model.mapping.tables.IngredientRecipeTable;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IngredientRecipeRecord extends TableRecordImpl<IngredientRecipeRecord> implements Record4<String, Integer, String, Integer> {

	private static final long serialVersionUID = 1703596318;

	/**
	 * Setter for <code>vegan_kitchen_api.ingredient_recipe.name</code>.
	 */
	public void setName(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>vegan_kitchen_api.ingredient_recipe.name</code>.
	 */
	public String getName() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>vegan_kitchen_api.ingredient_recipe.recipe_id</code>.
	 */
	public void setRecipeId(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>vegan_kitchen_api.ingredient_recipe.recipe_id</code>.
	 */
	public Integer getRecipeId() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>vegan_kitchen_api.ingredient_recipe.image_url</code>.
	 */
	public void setImageUrl(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>vegan_kitchen_api.ingredient_recipe.image_url</code>.
	 */
	public String getImageUrl() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>vegan_kitchen_api.ingredient_recipe.ingredient_id</code>.
	 */
	public void setIngredientId(Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>vegan_kitchen_api.ingredient_recipe.ingredient_id</code>.
	 */
	public Integer getIngredientId() {
		return (Integer) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<String, Integer, String, Integer> fieldsRow() {
		return (Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<String, Integer, String, Integer> valuesRow() {
		return (Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return IngredientRecipeTable.INGREDIENT_RECIPE.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return IngredientRecipeTable.INGREDIENT_RECIPE.RECIPE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return IngredientRecipeTable.INGREDIENT_RECIPE.IMAGE_URL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field4() {
		return IngredientRecipeTable.INGREDIENT_RECIPE.INGREDIENT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getRecipeId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getImageUrl();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value4() {
		return getIngredientId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IngredientRecipeRecord value1(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IngredientRecipeRecord value2(Integer value) {
		setRecipeId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IngredientRecipeRecord value3(String value) {
		setImageUrl(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IngredientRecipeRecord value4(Integer value) {
		setIngredientId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IngredientRecipeRecord values(String value1, Integer value2, String value3, Integer value4) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached IngredientRecipeRecord
	 */
	public IngredientRecipeRecord() {
		super(IngredientRecipeTable.INGREDIENT_RECIPE);
	}

	/**
	 * Create a detached, initialised IngredientRecipeRecord
	 */
	public IngredientRecipeRecord(String name, Integer recipeId, String imageUrl, Integer ingredientId) {
		super(IngredientRecipeTable.INGREDIENT_RECIPE);

		setValue(0, name);
		setValue(1, recipeId);
		setValue(2, imageUrl);
		setValue(3, ingredientId);
	}
}
