/**
 * This class is generated by jOOQ
 */
package model.mapping.tables.records;


import javax.annotation.Generated;

import model.mapping.tables.IngredientRecipeTable;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IngredientRecipeRecord extends TableRecordImpl<IngredientRecipeRecord> implements Record3<String, Integer, String> {

	private static final long serialVersionUID = -1988880773;

	/**
	 * Setter for <code>vegan_kitchen_api.ingredient_recipe.name</code>.
	 */
	public void setName(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>vegan_kitchen_api.ingredient_recipe.name</code>.
	 */
	public String getName() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>vegan_kitchen_api.ingredient_recipe.recipe_id</code>.
	 */
	public void setRecipeId(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>vegan_kitchen_api.ingredient_recipe.recipe_id</code>.
	 */
	public Integer getRecipeId() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>vegan_kitchen_api.ingredient_recipe.image_url</code>.
	 */
	public void setImageUrl(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>vegan_kitchen_api.ingredient_recipe.image_url</code>.
	 */
	public String getImageUrl() {
		return (String) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<String, Integer, String> fieldsRow() {
		return (Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<String, Integer, String> valuesRow() {
		return (Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return IngredientRecipeTable.INGREDIENT_RECIPE.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return IngredientRecipeTable.INGREDIENT_RECIPE.RECIPE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return IngredientRecipeTable.INGREDIENT_RECIPE.IMAGE_URL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getRecipeId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getImageUrl();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IngredientRecipeRecord value1(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IngredientRecipeRecord value2(Integer value) {
		setRecipeId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IngredientRecipeRecord value3(String value) {
		setImageUrl(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IngredientRecipeRecord values(String value1, Integer value2, String value3) {
		value1(value1);
		value2(value2);
		value3(value3);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached IngredientRecipeRecord
	 */
	public IngredientRecipeRecord() {
		super(IngredientRecipeTable.INGREDIENT_RECIPE);
	}

	/**
	 * Create a detached, initialised IngredientRecipeRecord
	 */
	public IngredientRecipeRecord(String name, Integer recipeId, String imageUrl) {
		super(IngredientRecipeTable.INGREDIENT_RECIPE);

		setValue(0, name);
		setValue(1, recipeId);
		setValue(2, imageUrl);
	}
}
