/**
 * This class is generated by jOOQ
 */
package model.mapping.tables.records;


import javax.annotation.Generated;

import model.mapping.tables.RecipeIngredientTable;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RecipeIngredientRecord extends UpdatableRecordImpl<RecipeIngredientRecord> implements Record5<Integer, Integer, String, String, String> {

	private static final long serialVersionUID = 1736751404;

	/**
	 * Setter for <code>vegan_kitchen_api.recipe_ingredient.recipe_id</code>.
	 */
	public void setRecipeId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>vegan_kitchen_api.recipe_ingredient.recipe_id</code>.
	 */
	public Integer getRecipeId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>vegan_kitchen_api.recipe_ingredient.ingredient_id</code>.
	 */
	public void setIngredientId(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>vegan_kitchen_api.recipe_ingredient.ingredient_id</code>.
	 */
	public Integer getIngredientId() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>vegan_kitchen_api.recipe_ingredient.name</code>.
	 */
	public void setName(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>vegan_kitchen_api.recipe_ingredient.name</code>.
	 */
	public String getName() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>vegan_kitchen_api.recipe_ingredient.amount</code>.
	 */
	public void setAmount(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>vegan_kitchen_api.recipe_ingredient.amount</code>.
	 */
	public String getAmount() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>vegan_kitchen_api.recipe_ingredient.image_url</code>.
	 */
	public void setImageUrl(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>vegan_kitchen_api.recipe_ingredient.image_url</code>.
	 */
	public String getImageUrl() {
		return (String) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Integer, Integer, String, String, String> fieldsRow() {
		return (Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Integer, Integer, String, String, String> valuesRow() {
		return (Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return RecipeIngredientTable.RECIPE_INGREDIENT.RECIPE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return RecipeIngredientTable.RECIPE_INGREDIENT.INGREDIENT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return RecipeIngredientTable.RECIPE_INGREDIENT.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return RecipeIngredientTable.RECIPE_INGREDIENT.AMOUNT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return RecipeIngredientTable.RECIPE_INGREDIENT.IMAGE_URL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getRecipeId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getIngredientId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getAmount();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getImageUrl();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecipeIngredientRecord value1(Integer value) {
		setRecipeId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecipeIngredientRecord value2(Integer value) {
		setIngredientId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecipeIngredientRecord value3(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecipeIngredientRecord value4(String value) {
		setAmount(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecipeIngredientRecord value5(String value) {
		setImageUrl(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecipeIngredientRecord values(Integer value1, Integer value2, String value3, String value4, String value5) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached RecipeIngredientRecord
	 */
	public RecipeIngredientRecord() {
		super(RecipeIngredientTable.RECIPE_INGREDIENT);
	}

	/**
	 * Create a detached, initialised RecipeIngredientRecord
	 */
	public RecipeIngredientRecord(Integer recipeId, Integer ingredientId, String name, String amount, String imageUrl) {
		super(RecipeIngredientTable.RECIPE_INGREDIENT);

		setValue(0, recipeId);
		setValue(1, ingredientId);
		setValue(2, name);
		setValue(3, amount);
		setValue(4, imageUrl);
	}
}
