/**
 * This class is generated by jOOQ
 */
package model.mapping.tables.records;


import javax.annotation.Generated;

import model.mapping.tables.RecipeTable;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RecipeRecord extends UpdatableRecordImpl<RecipeRecord> implements Record6<Integer, String, String, String, String, Integer> {

	private static final long serialVersionUID = 461926295;

	/**
	 * Setter for <code>vegan_kitchen_api.recipe.recipe_id</code>.
	 */
	public void setRecipeId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>vegan_kitchen_api.recipe.recipe_id</code>.
	 */
	public Integer getRecipeId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>vegan_kitchen_api.recipe.dish_name</code>.
	 */
	public void setDishName(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>vegan_kitchen_api.recipe.dish_name</code>.
	 */
	public String getDishName() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>vegan_kitchen_api.recipe.summary</code>.
	 */
	public void setSummary(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>vegan_kitchen_api.recipe.summary</code>.
	 */
	public String getSummary() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>vegan_kitchen_api.recipe.serving</code>.
	 */
	public void setServing(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>vegan_kitchen_api.recipe.serving</code>.
	 */
	public String getServing() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>vegan_kitchen_api.recipe.dish_image_url</code>.
	 */
	public void setDishImageUrl(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>vegan_kitchen_api.recipe.dish_image_url</code>.
	 */
	public String getDishImageUrl() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>vegan_kitchen_api.recipe.author_user_id</code>.
	 */
	public void setAuthorUserId(Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>vegan_kitchen_api.recipe.author_user_id</code>.
	 */
	public Integer getAuthorUserId() {
		return (Integer) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<Integer, String, String, String, String, Integer> fieldsRow() {
		return (Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<Integer, String, String, String, String, Integer> valuesRow() {
		return (Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return RecipeTable.RECIPE.RECIPE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return RecipeTable.RECIPE.DISH_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return RecipeTable.RECIPE.SUMMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return RecipeTable.RECIPE.SERVING;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return RecipeTable.RECIPE.DISH_IMAGE_URL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field6() {
		return RecipeTable.RECIPE.AUTHOR_USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getRecipeId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getDishName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getSummary();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getServing();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getDishImageUrl();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value6() {
		return getAuthorUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecipeRecord value1(Integer value) {
		setRecipeId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecipeRecord value2(String value) {
		setDishName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecipeRecord value3(String value) {
		setSummary(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecipeRecord value4(String value) {
		setServing(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecipeRecord value5(String value) {
		setDishImageUrl(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecipeRecord value6(Integer value) {
		setAuthorUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecipeRecord values(Integer value1, String value2, String value3, String value4, String value5, Integer value6) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached RecipeRecord
	 */
	public RecipeRecord() {
		super(RecipeTable.RECIPE);
	}

	/**
	 * Create a detached, initialised RecipeRecord
	 */
	public RecipeRecord(Integer recipeId, String dishName, String summary, String serving, String dishImageUrl, Integer authorUserId) {
		super(RecipeTable.RECIPE);

		setValue(0, recipeId);
		setValue(1, dishName);
		setValue(2, summary);
		setValue(3, serving);
		setValue(4, dishImageUrl);
		setValue(5, authorUserId);
	}
}
