/**
 * This class is generated by jOOQ
 */
package model.mapping.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Logging implements Serializable {

	private static final long serialVersionUID = -413012527;

	private Integer userId;
	private String  sessionId;

	public Logging() {}

	public Logging(Logging value) {
		this.userId = value.userId;
		this.sessionId = value.sessionId;
	}

	public Logging(
		Integer userId,
		String  sessionId
	) {
		this.userId = userId;
		this.sessionId = sessionId;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getSessionId() {
		return this.sessionId;
	}

	public void setSessionId(String sessionId) {
		this.sessionId = sessionId;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("Logging (");

		sb.append(userId);
		sb.append(", ").append(sessionId);

		sb.append(")");
		return sb.toString();
	}
}
