/**
 * This class is generated by jOOQ
 */
package model.mapping.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RecipeIngredient implements Serializable {

	private static final long serialVersionUID = 1625215833;

	private Integer recipeId;
	private Integer ingredientId;
	private String  name;
	private String  amount;
	private String  imageUrl;

	public RecipeIngredient() {}

	public RecipeIngredient(RecipeIngredient value) {
		this.recipeId = value.recipeId;
		this.ingredientId = value.ingredientId;
		this.name = value.name;
		this.amount = value.amount;
		this.imageUrl = value.imageUrl;
	}

	public RecipeIngredient(
		Integer recipeId,
		Integer ingredientId,
		String  name,
		String  amount,
		String  imageUrl
	) {
		this.recipeId = recipeId;
		this.ingredientId = ingredientId;
		this.name = name;
		this.amount = amount;
		this.imageUrl = imageUrl;
	}

	public Integer getRecipeId() {
		return this.recipeId;
	}

	public void setRecipeId(Integer recipeId) {
		this.recipeId = recipeId;
	}

	public Integer getIngredientId() {
		return this.ingredientId;
	}

	public void setIngredientId(Integer ingredientId) {
		this.ingredientId = ingredientId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAmount() {
		return this.amount;
	}

	public void setAmount(String amount) {
		this.amount = amount;
	}

	public String getImageUrl() {
		return this.imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("RecipeIngredient (");

		sb.append(recipeId);
		sb.append(", ").append(ingredientId);
		sb.append(", ").append(name);
		sb.append(", ").append(amount);
		sb.append(", ").append(imageUrl);

		sb.append(")");
		return sb.toString();
	}
}
