/**
 * This class is generated by jOOQ
 */
package model.mapping.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RecipeInstruction implements Serializable {

	private static final long serialVersionUID = -1331902274;

	private Integer recipeId;
	private Integer instructionId;
	private String  instruction;
	private String  imageUrl;

	public RecipeInstruction() {}

	public RecipeInstruction(RecipeInstruction value) {
		this.recipeId = value.recipeId;
		this.instructionId = value.instructionId;
		this.instruction = value.instruction;
		this.imageUrl = value.imageUrl;
	}

	public RecipeInstruction(
		Integer recipeId,
		Integer instructionId,
		String  instruction,
		String  imageUrl
	) {
		this.recipeId = recipeId;
		this.instructionId = instructionId;
		this.instruction = instruction;
		this.imageUrl = imageUrl;
	}

	public Integer getRecipeId() {
		return this.recipeId;
	}

	public void setRecipeId(Integer recipeId) {
		this.recipeId = recipeId;
	}

	public Integer getInstructionId() {
		return this.instructionId;
	}

	public void setInstructionId(Integer instructionId) {
		this.instructionId = instructionId;
	}

	public String getInstruction() {
		return this.instruction;
	}

	public void setInstruction(String instruction) {
		this.instruction = instruction;
	}

	public String getImageUrl() {
		return this.imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("RecipeInstruction (");

		sb.append(recipeId);
		sb.append(", ").append(instructionId);
		sb.append(", ").append(instruction);
		sb.append(", ").append(imageUrl);

		sb.append(")");
		return sb.toString();
	}
}
