/**
 * This class is generated by jOOQ
 */
package model.mapping.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserAttempt implements Serializable {

	private static final long serialVersionUID = 656270236;

	private Integer userId;
	private Integer attemptNumber;
	private String  message;
	private String  sessionId;

	public UserAttempt() {}

	public UserAttempt(UserAttempt value) {
		this.userId = value.userId;
		this.attemptNumber = value.attemptNumber;
		this.message = value.message;
		this.sessionId = value.sessionId;
	}

	public UserAttempt(
		Integer userId,
		Integer attemptNumber,
		String  message,
		String  sessionId
	) {
		this.userId = userId;
		this.attemptNumber = attemptNumber;
		this.message = message;
		this.sessionId = sessionId;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public Integer getAttemptNumber() {
		return this.attemptNumber;
	}

	public void setAttemptNumber(Integer attemptNumber) {
		this.attemptNumber = attemptNumber;
	}

	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public String getSessionId() {
		return this.sessionId;
	}

	public void setSessionId(String sessionId) {
		this.sessionId = sessionId;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("UserAttempt (");

		sb.append(userId);
		sb.append(", ").append(attemptNumber);
		sb.append(", ").append(message);
		sb.append(", ").append(sessionId);

		sb.append(")");
		return sb.toString();
	}
}
