/**
 * This class is generated by jOOQ
 */
package model.mapping.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import model.mapping.Keys;
import model.mapping.VeganKitchenApiSchema;
import model.mapping.tables.records.LoggingRecord;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LoggingTable extends TableImpl<LoggingRecord> {

	private static final long serialVersionUID = -325505518;

	/**
	 * The reference instance of <code>vegan_kitchen_api.logging</code>
	 */
	public static final LoggingTable LOGGING = new LoggingTable();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<LoggingRecord> getRecordType() {
		return LoggingRecord.class;
	}

	/**
	 * The column <code>vegan_kitchen_api.logging.user_id</code>.
	 */
	public final TableField<LoggingRecord, Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>vegan_kitchen_api.logging.session_id</code>.
	 */
	public final TableField<LoggingRecord, String> SESSION_ID = createField("session_id", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>vegan_kitchen_api.logging.exception</code>.
	 */
	public final TableField<LoggingRecord, String> EXCEPTION = createField("exception", org.jooq.impl.SQLDataType.VARCHAR.length(225), this, "");

	/**
	 * The column <code>vegan_kitchen_api.logging.message</code>.
	 */
	public final TableField<LoggingRecord, String> MESSAGE = createField("message", org.jooq.impl.SQLDataType.VARCHAR.length(500), this, "");

	/**
	 * Create a <code>vegan_kitchen_api.logging</code> table reference
	 */
	public LoggingTable() {
		this("logging", null);
	}

	/**
	 * Create an aliased <code>vegan_kitchen_api.logging</code> table reference
	 */
	public LoggingTable(String alias) {
		this(alias, LOGGING);
	}

	private LoggingTable(String alias, Table<LoggingRecord> aliased) {
		this(alias, aliased, null);
	}

	private LoggingTable(String alias, Table<LoggingRecord> aliased, Field<?>[] parameters) {
		super(alias, VeganKitchenApiSchema.VEGAN_KITCHEN_API, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<LoggingRecord>> getKeys() {
		return Arrays.<UniqueKey<LoggingRecord>>asList(Keys.KEY_LOGGING_USER_ID, Keys.KEY_LOGGING_SESSION_ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LoggingTable as(String alias) {
		return new LoggingTable(alias, this);
	}

	/**
	 * Rename this table
	 */
	public LoggingTable rename(String name) {
		return new LoggingTable(name, null);
	}
}
