/**
 * This class is generated by jOOQ
 */
package model.mapping.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import model.mapping.Keys;
import model.mapping.VeganKitchenApiSchema;
import model.mapping.tables.records.RecipeInstructionRecord;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RecipeInstructionTable extends TableImpl<RecipeInstructionRecord> {

	private static final long serialVersionUID = -1006347101;

	/**
	 * The reference instance of <code>vegan_kitchen_api.recipe_instruction</code>
	 */
	public static final RecipeInstructionTable RECIPE_INSTRUCTION = new RecipeInstructionTable();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<RecipeInstructionRecord> getRecordType() {
		return RecipeInstructionRecord.class;
	}

	/**
	 * The column <code>vegan_kitchen_api.recipe_instruction.recipe_id</code>.
	 */
	public final TableField<RecipeInstructionRecord, Integer> RECIPE_ID = createField("recipe_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>vegan_kitchen_api.recipe_instruction.instruction_id</code>.
	 */
	public final TableField<RecipeInstructionRecord, Integer> INSTRUCTION_ID = createField("instruction_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>vegan_kitchen_api.recipe_instruction.step_number</code>.
	 */
	public final TableField<RecipeInstructionRecord, Integer> STEP_NUMBER = createField("step_number", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>vegan_kitchen_api.recipe_instruction.instruction</code>.
	 */
	public final TableField<RecipeInstructionRecord, String> INSTRUCTION = createField("instruction", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>vegan_kitchen_api.recipe_instruction.image_url</code>.
	 */
	public final TableField<RecipeInstructionRecord, String> IMAGE_URL = createField("image_url", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>vegan_kitchen_api.recipe_instruction</code> table reference
	 */
	public RecipeInstructionTable() {
		this("recipe_instruction", null);
	}

	/**
	 * Create an aliased <code>vegan_kitchen_api.recipe_instruction</code> table reference
	 */
	public RecipeInstructionTable(String alias) {
		this(alias, RECIPE_INSTRUCTION);
	}

	private RecipeInstructionTable(String alias, Table<RecipeInstructionRecord> aliased) {
		this(alias, aliased, null);
	}

	private RecipeInstructionTable(String alias, Table<RecipeInstructionRecord> aliased, Field<?>[] parameters) {
		super(alias, VeganKitchenApiSchema.VEGAN_KITCHEN_API, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<RecipeInstructionRecord, Integer> getIdentity() {
		return Keys.IDENTITY_RECIPE_INSTRUCTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<RecipeInstructionRecord> getPrimaryKey() {
		return Keys.KEY_RECIPE_INSTRUCTION_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<RecipeInstructionRecord>> getKeys() {
		return Arrays.<UniqueKey<RecipeInstructionRecord>>asList(Keys.KEY_RECIPE_INSTRUCTION_PRIMARY, Keys.KEY_RECIPE_INSTRUCTION_INSTRUCTION_ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecipeInstructionTable as(String alias) {
		return new RecipeInstructionTable(alias, this);
	}

	/**
	 * Rename this table
	 */
	public RecipeInstructionTable rename(String name) {
		return new RecipeInstructionTable(name, null);
	}
}
