/**
 * This class is generated by jOOQ
 */
package model.mapping.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import model.mapping.Keys;
import model.mapping.VeganKitchenApiSchema;
import model.mapping.tables.records.RecipeIngredientRecord;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RecipeIngredientTable extends TableImpl<RecipeIngredientRecord> {

	private static final long serialVersionUID = 1763558853;

	/**
	 * The reference instance of <code>vegan_kitchen_api.recipe_ingredient</code>
	 */
	public static final RecipeIngredientTable RECIPE_INGREDIENT = new RecipeIngredientTable();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<RecipeIngredientRecord> getRecordType() {
		return RecipeIngredientRecord.class;
	}

	/**
	 * The column <code>vegan_kitchen_api.recipe_ingredient.recipe_id</code>.
	 */
	public final TableField<RecipeIngredientRecord, Integer> RECIPE_ID = createField("recipe_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>vegan_kitchen_api.recipe_ingredient.ingredient_id</code>.
	 */
	public final TableField<RecipeIngredientRecord, Integer> INGREDIENT_ID = createField("ingredient_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>vegan_kitchen_api.recipe_ingredient.name</code>.
	 */
	public final TableField<RecipeIngredientRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

	/**
	 * The column <code>vegan_kitchen_api.recipe_ingredient.amount</code>.
	 */
	public final TableField<RecipeIngredientRecord, String> AMOUNT = createField("amount", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

	/**
	 * The column <code>vegan_kitchen_api.recipe_ingredient.image_url</code>.
	 */
	public final TableField<RecipeIngredientRecord, String> IMAGE_URL = createField("image_url", org.jooq.impl.SQLDataType.VARCHAR.length(225), this, "");

	/**
	 * Create a <code>vegan_kitchen_api.recipe_ingredient</code> table reference
	 */
	public RecipeIngredientTable() {
		this("recipe_ingredient", null);
	}

	/**
	 * Create an aliased <code>vegan_kitchen_api.recipe_ingredient</code> table reference
	 */
	public RecipeIngredientTable(String alias) {
		this(alias, RECIPE_INGREDIENT);
	}

	private RecipeIngredientTable(String alias, Table<RecipeIngredientRecord> aliased) {
		this(alias, aliased, null);
	}

	private RecipeIngredientTable(String alias, Table<RecipeIngredientRecord> aliased, Field<?>[] parameters) {
		super(alias, VeganKitchenApiSchema.VEGAN_KITCHEN_API, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<RecipeIngredientRecord, Integer> getIdentity() {
		return Keys.IDENTITY_RECIPE_INGREDIENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<RecipeIngredientRecord> getPrimaryKey() {
		return Keys.KEY_RECIPE_INGREDIENT_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<RecipeIngredientRecord>> getKeys() {
		return Arrays.<UniqueKey<RecipeIngredientRecord>>asList(Keys.KEY_RECIPE_INGREDIENT_PRIMARY, Keys.KEY_RECIPE_INGREDIENT_INGREDIENT_ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecipeIngredientTable as(String alias) {
		return new RecipeIngredientTable(alias, this);
	}

	/**
	 * Rename this table
	 */
	public RecipeIngredientTable rename(String name) {
		return new RecipeIngredientTable(name, null);
	}
}
