/**
 * This class is generated by jOOQ
 */
package model.mapping.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import model.mapping.Keys;
import model.mapping.VeganKitchenApiSchema;
import model.mapping.tables.records.UserAttemptRecord;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserAttemptTable extends TableImpl<UserAttemptRecord> {

	private static final long serialVersionUID = -1745152820;

	/**
	 * The reference instance of <code>vegan_kitchen_api.user_attempt</code>
	 */
	public static final UserAttemptTable USER_ATTEMPT = new UserAttemptTable();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<UserAttemptRecord> getRecordType() {
		return UserAttemptRecord.class;
	}

	/**
	 * The column <code>vegan_kitchen_api.user_attempt.user_id</code>.
	 */
	public final TableField<UserAttemptRecord, Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>vegan_kitchen_api.user_attempt.attempt_number</code>.
	 */
	public final TableField<UserAttemptRecord, Integer> ATTEMPT_NUMBER = createField("attempt_number", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>vegan_kitchen_api.user_attempt.message</code>.
	 */
	public final TableField<UserAttemptRecord, String> MESSAGE = createField("message", org.jooq.impl.SQLDataType.VARCHAR.length(225).nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>vegan_kitchen_api.user_attempt.session_id</code>.
	 */
	public final TableField<UserAttemptRecord, String> SESSION_ID = createField("session_id", org.jooq.impl.SQLDataType.VARCHAR.length(225).nullable(false), this, "");

	/**
	 * Create a <code>vegan_kitchen_api.user_attempt</code> table reference
	 */
	public UserAttemptTable() {
		this("user_attempt", null);
	}

	/**
	 * Create an aliased <code>vegan_kitchen_api.user_attempt</code> table reference
	 */
	public UserAttemptTable(String alias) {
		this(alias, USER_ATTEMPT);
	}

	private UserAttemptTable(String alias, Table<UserAttemptRecord> aliased) {
		this(alias, aliased, null);
	}

	private UserAttemptTable(String alias, Table<UserAttemptRecord> aliased, Field<?>[] parameters) {
		super(alias, VeganKitchenApiSchema.VEGAN_KITCHEN_API, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<UserAttemptRecord>> getKeys() {
		return Arrays.<UniqueKey<UserAttemptRecord>>asList(Keys.KEY_USER_ATTEMPT_USER_ID, Keys.KEY_USER_ATTEMPT_SESSION_ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserAttemptTable as(String alias) {
		return new UserAttemptTable(alias, this);
	}

	/**
	 * Rename this table
	 */
	public UserAttemptTable rename(String name) {
		return new UserAttemptTable(name, null);
	}
}
